name: Main branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Build and test the app
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run tests
        run: cd tests/ && poetry run python run.py

      # Build docker image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Export requirements.txt
        run: poetry export -f requirements.txt --output requirements.txt
      - name: Docker build
        run: docker build --build-arg OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} -t dialbot:latest .
      - name: Save docker image to tarball
        run: docker save dialbot:latest -o dialbot-docker-image.tar

      # Manually publish docker image to server
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DIALBOT_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DIALBOT_SERVER_HOST }} >> ~/.ssh/known_hosts
      - name: Scp docker image to server
        run: scp -i ~/.ssh/id_rsa dialbot-docker-image.tar root@${{ secrets.DIALBOT_SERVER_HOST }}:/home/dialbot-docker-image.tar
