name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: ./.github/actions/setup
      - name: Run tests
        run: cd tests/ && poetry run python run.py
      - name: Build and publish
        run: |
         poetry build
#         poetry publish --build
